name: Deploy

on:
  workflow_run:
    workflows: [Lint Code Base]
    types:
      - completed

jobs:
  build:
    name: Deploy to prod
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: loakiwi/app
          tag: ci-cd_test
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}