name: Deploy

on:
  workflow_run:
    workflows: [Lint Code Base]
    types:
      - completed

jobs:
  build:
    name: Deploy to prod
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: loakiwi/app
          tags: v1, latest
          registry: registry-url.io
          dockerfile: dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}